//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.PGJ.SistemaPolizas.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egresos
    {
        public int Id { get; set; }
        public System.DateTime FechaDeEgreso { get; set; }
        public decimal Cantidad { get; set; }
        public int DetalleUsuarioId { get; set; }
        public string Descripcion { get; set; }
        public int MinisteriosPublicosId { get; set; }
    
        public virtual DetallesUsuarios DetallesUsuarios { get; set; }
        public virtual MinisteriosPublicos MinisteriosPublicos { get; set; }
    }
}
