//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.PGJ.SistemaPolizas.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public int Id { get; set; }
        public decimal Cantidad { get; set; }
        public int PolizaId { get; set; }
        public System.DateTime FechaDeIngreso { get; set; }
        public int DepositanteId { get; set; }
        public string Descripcion { get; set; }
        public int DetalleUsuarioId { get; set; }
    
        public virtual Depositantes Depositantes { get; set; }
        public virtual DetallesUsuarios DetallesUsuarios { get; set; }
        public virtual Polizas Polizas { get; set; }
    }
}
