//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.PGJ.SistemaPolizas.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinisteriosPublicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MinisteriosPublicos()
        {
            this.Egresos = new HashSet<Egresos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> AutoridadId { get; set; }
    
        public virtual Autoridads Autoridads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egresos> Egresos { get; set; }
    }
}
