//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.PGJ.SistemaPolizas.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PGJSistemaPolizasEntities : DbContext
    {
        public PGJSistemaPolizasEntities()
            : base("name=PGJSistemaPolizasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afianzadoras> Afianzadoras { get; set; }
        public virtual DbSet<Afianzados> Afianzados { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Autoridads> Autoridads { get; set; }
        public virtual DbSet<Depositantes> Depositantes { get; set; }
        public virtual DbSet<DetallesUsuarios> DetallesUsuarios { get; set; }
        public virtual DbSet<Egresos> Egresos { get; set; }
        public virtual DbSet<Ingresos> Ingresos { get; set; }
        public virtual DbSet<MinisteriosPublicos> MinisteriosPublicos { get; set; }
        public virtual DbSet<Polizas> Polizas { get; set; }
    }
}
