//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.PGJ.SistemaPolizas.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polizas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polizas()
        {
            this.Cantidad = 0m;
            this.Ingresos = new HashSet<Ingresos>();
        }
    
        public int Id { get; set; }
        public string AveriguacionPrevia { get; set; }
        public int AfianzadoraId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaDeAlta { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    
        public virtual Afianzadoras Afianzadoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        public virtual Afianzados Afianzado { get; set; }
    }
}
